spring:
  application:
    name: SpringBoot-Jersey

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

server:
  port: 8888

swagger:
  title: API文档
  version: 1.0
  contact: Aaron
  basePath: /api
  resourcePackege: com.aaron.api
